version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-stepbystep
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stepbystep
      MYSQL_USER: study
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - step-network

networks:
  step-network:
    driver: bridge